### ISSUE TITLE
Flash error for TWRP 3.3.1.0

### ISSUE THREAD

**Issue by EEMuk** [sailfish-santoni/projectmanagement#1]
Getting error 7 in twrp tried older twrps same error.
logs,
Installing zip file '/external_sd/roms/sailfishos-santoni-release-3.0.3.10-danctnix.zip'
Checking for Digest file...
I:Update binary zip
Verifying package compatibility...
Package doesn't contain compatibility.zip entry
I:Extracting updater binary 'META-INF/com/google/android/update-binary'
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment not used in updater.
selinux_android_file_context: Error getting file context handle (No such file or directory)
Warning: No file_contexts
========================================
========================================Hybris Installer
Hybris Installer========================================
========================================      Device: santoni
      Device: santoni     Version: 3.0.3.10
     Version: 3.0.3.10       Image: sailfishos-santoni-release-3.0.3.10-danctnix.tar.bz2
       Image: sailfishos-santoni-release-3.0.3.10-danctnix.tar.bz2        Size: 337M
        Size: 337M  Partitions:
  Partitions:    /boot -> /dev/block/bootdevice/by-name/boot
    /boot -> /dev/block/bootdevice/by-name/boot    /data -> /dev/block/bootdevice/by-name/userdata
    /data -> /dev/block/bootdevice/by-name/userdata========================================
========================================
Device check succeeded, mounting filesystems ...
Device check succeeded, mounting filesystems ...detected filesystem ext4 for /dev/block/bootdevice/by-name/userdatadetected filesystem ext4 for /dev/block/bootdevice/by-name/userdata

mount: Failed to mount /dev/block/bootdevice/by-name/userdata at /data: Device or resource busy
mount: Failed to mount /dev/block/bootdevice/by-name/userdata at /data: Device or resource busyCopying filesystem archive ...
Copying filesystem archive ...Copying installation script ...
Copying installation script ...Running installation script ...
Running installation script ...about to run program [/tmp/updater-unpack.sh] with 1 args
tar: exec bunzip2: No such file or directory
tar: read error
run_program: child exited with status 1
script aborted: Failed to extract filesystem!
Failed to extract filesystem!error: 25
Updater process ended with ERROR: 7
I:Install took 12 second(s).
Error installing zip file '/external_sd/roms/sailfishos-santoni-release-3.0.3.10-danctnix.zip'
Updating partition details...

**Comment by Danct12** [comment]
bunzip2 error seems to be weird, can you tell me where did you get your TWRP from?

During our testing, we used https://dl.twrp.me/santoni/twrp-3.3.1-0-santoni.img.html

**Comment by EEMuk** [comment]
yes it is the same TWRP

**Comment by Danct12** [comment]
Probably will work again when you try flashing the same sfos zip again the second time after you get the error, that's the same issue I had while flashing.

**Comment by EEMuk** [comment]
Rom file is lineage os 14.1 by issacchen  https://androidfilehost.com/?fid=674106145207485749

**Comment by Danct12** [comment]
You also don't flash LineageOS 14.1, you use official 15.1 from LineageOS.

**Comment by EEMuk** [comment]
in the post it says Lineage OS 14.1!!

**Comment by Danct12** [comment]
Oh, it really is? Sorry, that's my fault, fixing it right now.

**Comment by EEMuk** [comment]
ok i will try with Lineage OS 15.1
