### ISSUE TITLE
Calling issue

### ISSUE THREAD

**Issue by EEMuk** [sailfish-santoni/projectmanagement#2]
Calling to a number works also can receive call but receiver and mic are not working no sound on both side.
Tried on both 2/3/4 G networks.

**Comment by Danct12** [comment]
Can you try to turn on speakerphone and turn off to see if that can do anything? We're currently using a hacky script to get calls working, which may not work as expected on some people.

**Comment by EEMuk** [comment]
Tried turning on and off the speaker and even on headphones, same result not working on them also.

**Comment by Danct12** [comment]
@asriel-danctnix, can you investigate this? I currently don't have my phone with me right now.
Meanwhile, it would be very useful if you could take a logcat, journalctl when on a call

**Comment by asriel-danctnix** [comment]
I think @jusa did told us in #sailfishos-porters IRC channel about [this module](https://github.com/jusa/pulseaudio-modules-droid-hidl), I haven't tested it yet but taking a look at that very soon.

Will keeping you all updated.

**Comment by asriel-danctnix** [comment]
@muk420 Can you install this package (using rpm -i): https://github.com/sailfish-santoni/temp-rpms/blob/master/pulseaudio-modules-droid-hidl-1.0-1.armv7hl.rpm

Then disable our hacky script `systemctl --user disable callaudiod` (as nemo), add `load-module module-droid-hidl` to `/etc/pulse/arm_droid_default.pa` and restart the device. Let me know if calling is resolved after that.

**Comment by Danct12** [comment]
Can confirm that doing what @asriel-danctnix said made calls working properly again without a hacky script! \o/

I'll push a second release soon once I could find more stuffs that aren't working.
