### ISSUE TITLE
LOS 15.1 unavailable now for santoni, any plans on updates ?

### ISSUE THREAD

**Issue by gbowsky** [sailfish-santoni/projectmanagement#3]
Now here is Lineage OS 16 builds only. Any updates planned, 3.1.0.11 ?
![image](https://user-images.githubusercontent.com/36237725/68040899-5b87a180-fce0-11e9-9d00-63f3d06bb2ea.png)

**Comment by Danct12** [comment]
You should be able to obtain a copy of the latest LOS build as a SailfishOS release.
https://github.com/sailfish-santoni/projectmanagement/releases/download/1.0-alpha/lineage-15.1-20190726-nightly-santoni-signed.zip

EDIT: You may want to do this after install: https://github.com/sailfish-santoni/projectmanagement/issues/2#issuecomment-518714027
